#ここに本来controllers.coffeeである記述を行う

angular.module('starter.controllers', [])
.controller('DashCtrl', ($scope) ->
  $("#buttestok").click =>
    converter = new showdown.Converter()
    converter.setOption('tables', 'true')
    input_word = document.getElementById("memotest").value
    mark2html = converter.makeHtml(input_word)
    console.log mark2html
    
    
    console.log $(':focus')
)

.controller('TestCtrl', ($scope) ->
  #cpm_tom = new Cpm_tom()
  edit_memo = new Edit_memo()
  
  $("#insert_h2").click =>
    new Insert_caret("memosd", "## ")
  
  $("#insert_yoko").click =>
    new Insert_caret("memosd", "\n---\n")
    
  $("#insert_list").click =>
    new Insert_caret("memosd", "- ")
    
  $("#insert_hutoi").click =>
    new Insert_caret("memosd", "**input**")
    
  $("#insert_bq").click =>
    new Insert_caret("memosd", "> ")
  
  $("#insert_strikethrough").click =>
    new Insert_caret("memosd", "~~ input ~~")

  $("#insert_home").click =>
    $text_area = $('#memosd')
    $text_area.attr('selectionEnd', 0)
    $text_area.attr('selectionStart', 0)
    $text_area.focus()

  
  $("#insert_end").click =>
    new Insert_caret("memosd", "~~ input ~~")
  
  $('#memosd').css
    "resize": "none"
  area_auto_size = new Area_auto_size("memosd")

  
  $("#memosd").keyup ->
    console.log "keyup"
    edit_memo.save()
    
  $scope.$on '$ionicView.enter', (event, data) ->
    edit_memo = new Edit_memo()

      
      
)

.controller('ChatsCtrl', ($scope) ->
  $scope.$on '$ionicView.enter', (event, data) ->
    select_memo_disp = new Select_memo_disp("str33")
    select_memo_disp.title_memo_disp()
    
    
  
)

.controller 'AccountCtrl', ($scope) ->
  $scope.$on '$ionicView.enter', (event, data) ->
    new Disp("accountdisp").delete()
    addradio = new Add_radio("accountdisp", "betu")
    addradio.story1()
    addradio.story2()
    addradio.story3()
  $("#add_title").click =>
    test111 = new Add_title("input_title")
    test111.story1()
  $("#delete").click =>
    new Delete_button()

# ---
# generated by js2coffee 2.2.0s