#ここに本来controllers.coffeeである記述を行う

angular.module('starter.controllers', [])
.controller('DashCtrl', ($scope) ->
  $("#buttestok").click =>
    doAfter = ->
      $('#memotest').focus()
  
    setTimeout(doAfter, 10)

# ---
# generated by js2coffee 2.2.0
    
    #console.log $(':focus')
)

.controller('TestCtrl', ($scope) ->
  #cpm_tom = new Cpm_tom()
  edit_memo = new Edit_memo()
  
  $('#memosd').css
    "resize": "none"
  area_auto_size = new Area_auto_size("memosd")
  
  $scope.$on '$ionicView.enter', (event, data) ->
    edit_memo = new Edit_memo()
    area_auto_size.story1()
    $('#memosd').focus()


  $("#memosd").keyup ->
    console.log "keyup"
    edit_memo.save()
    
  $("#titled").keyup ->
    edit_memo.save()
    

  
  
  $("#insert_h2").click =>
    doAfter = ->
      new Insert_caret("memosd", "## ")
      area_auto_size.story1()
      edit_memo.save()
    setTimeout(doAfter, 10)
  
  $("#insert_yoko").click =>
    doAfter = ->
      new Insert_caret("memosd", "\n---\n")
      area_auto_size.story1()
      edit_memo.save()
    setTimeout(doAfter, 10)
    
  $("#insert_list").click =>
    doAfter = ->
      new Insert_caret("memosd", "- ")
      area_auto_size.story1()
      edit_memo.save()
    setTimeout(doAfter, 10)
    
  $("#insert_hutoi").click =>
    doAfter = ->
      new Insert_caret("memosd", "**input**")
      area_auto_size.story1()
      edit_memo.save()
    setTimeout(doAfter, 10)
    
  $("#insert_bq").click =>
    doAfter = ->
      new Insert_caret("memosd", "> ")
      area_auto_size.story1()
      edit_memo.save()
    setTimeout(doAfter, 10)
    
  $("#insert_strikethrough").click =>
    doAfter = ->
      new Insert_caret("memosd", "~~ input ~~")
      area_auto_size.story1()
      edit_memo.save()
    setTimeout(doAfter, 10)
    
  $("#insert_home").click =>
    doAfter = ->
      new End_and_home().home()
      area_auto_size.story1()
      edit_memo.save()
    setTimeout(doAfter, 10)
  
  $("#insert_end").click =>
    doAfter = ->
      new End_and_home().end()
      area_auto_size.story1()
      edit_memo.save()
    setTimeout(doAfter, 10)
  

      
      
)

.controller('ChatsCtrl', ($scope) ->
  $scope.$on '$ionicView.enter', (event, data) ->
    select_memo_disp = new Select_memo_disp("str33")
    select_memo_disp.title_memo_disp()
    
    
  
)

.controller 'AccountCtrl', ($scope) ->
  $scope.$on '$ionicView.enter', (event, data) ->
    new Disp("accountdisp").delete()
    addradio = new Add_radio("accountdisp", "betu")
    addradio.story1()
    addradio.story2()
    addradio.story3()
  $("#add_title").click =>
    test111 = new Add_title("input_title")
    test111.story1()
  $("#delete").click =>
    myRet = confirm("delete ?")
    if myRet == true
      new Delete_button()
    

# ---
# generated by js2coffee 2.2.0s